### ISSUE TITLE
Question: Display manager + Theme?

### ISSUE THREAD

**Issue by pinpox** [dreamsmasher/dotfiles#1]
Hi, quick question,
I saw your post over here:

https://www.reddit.com/r/unixporn/comments/ecgmy9/oc_i_turned_a_blender_animation_somebody_posted_a/

What display manager is that at the end of the video? LigthDM? Would you mind sharing the config?

Thanks!

**Comment by dreamsmasher** [comment]
Yeah, it's just lightdm with the webkit2 greeter and aether theme. I did most of my configuration in the login page itself. Don't know exactly where the config is stored for when you tweak the CSS inside the greeter page :/

**Comment by pinpox** [comment]
Thanks for the info, will look up that theme!
